version: '2'
services:

    elasticsearch:
      images: ypereirareis/elasticsearch-head
      container_name: elasticsearch
      ports:
        - "9200:9200"
        - "9300:9300"
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

    fluentd-es:
      build:
        context: ./../images/fluentd-es
      container_name: fluentd-es
      ports:
        - 24224:24224
        - 8080:8080
      environment:
        - ES_BROWSER_HOST=localhost
        - ES_HOST=elasticsearch
        - ES_PORT=9200
        - ES_INDEX=fluentd
      depends_on:
        - elasticsearch
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
