sudo: required

language: dart

dart:
  # Install the latest stable release
  - stable

env:
  global:
     - CURRENT=$(pwd)
     - DOCKER_REPOSITORY=bwnyasse/led
     - DOCKER_COMPOSE_VERSION=1.8.0

     # LED build version - also used to tag github repo and docker hub image
     - VERSION=0.4.0-SNAPSHOT

services:
  - docker

before_install:
  # Check current docker engine version
  - docker --version

  # Installing docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  # set env vars in the build settings to interact with repositories
  # see https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
  - echo "Testing Docker Hub credentials"
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD

before_install:
   # update UI
  - ./bin/build_ui.sh

install:
  - cd $CURRENT/images/led
  - docker pull ${DOCKER_REPOSITORY}:latest || true
  - docker build -t ${DOCKER_REPOSITORY} --pull=true --build-arg version=${VERSION} .
  - docker build -t ${DOCKER_REPOSITORY}:${VERSION} --build-arg version=${VERSION} .

script:
  - cd $CURRENT/integ/dev
  - docker-compose -f led.yml up --build --force-recreate --remove-orphans -d
  - docker-compose -f service.yml up --build --force-recreate -d
  - count=$(docker ps -aq -f status="running" -s | wc -l)
  - if [[  $count != 3 ]]; then echo "Expected 3 running containers" && exit 1 ; fi
  - cd $CURRENT

before_deploy:
   # CREATE GIT TAG
  - ./bin/github.sh

deploy:

    # Deploy to docker hub
    provider: script
    script: ./bin/dockerhub.sh
    skip_cleanup: true
    on:
      branch: master
