#============================================================================================================#
#description     : docker compose YAML file used to launch Integrations Tests for Led
#author		       :bwnyasse
#===========================================================================================================#
version: '2'
services:

    # Basic LED
    led:
      #image: bwnyasse/led
      build:
        context: ../../images/led
      container_name: led
      ports:
        - 24224:24224
        - 8082:8082
        - 8080:8080
        - 7777:7777
        # - 9200:9200
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
