#============================================================================================================#
#description     : docker compose YAML file used to launch Integrations Tests for Service
#author		       :bwnyasse
#===========================================================================================================#
version: '2'
services:

    # Wildfly 10.0.0.Final
    wildfly:
      build:
        context: ./javaee/wildfly.10
      container_name: wildfly
      logging:
        driver: fluentd
        options:
          tag: "wildfly.docker.{{.Name }}"
          fluentd-address: localhost:24224
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

    # wildfly swarm 1.0.0.Final
    # wildfly_swarm:
    #   build:
    #     context: ./javaee/wildfly-swarm
    #   container_name:  wildfly_swarm
    #   logging:
    #     driver: fluentd
    #     options:
    #       tag: "wildfly.docker.{{.Name }}"
    #       fluentd-address: localhost:24224
    #   volumes:
    #     - /etc/localtime:/etc/localtime:ro
    #     - /etc/timezone:/etc/timezone:ro

    # Custom
    custom-container:
      build:
        context: ./custom
      container_name: custom_container
      # logging:
      #   driver: fluentd
      #   options:
      #     tag: "default.docker.{{.Name }}"
      #     fluentd-address: localhost:24224
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

    # Mongo Db Instance
    mongodb:
      image: mongo:3.2.8
      ports:
        - "27017:27017"
        - "28017:28017"
      container_name: mongodb
      logging:
        driver: fluentd
        options:
          tag: "mongo.docker.{{.Name }}"
          fluentd-address: localhost:24224
      volumes:
        - /etc/localtime:/etc/localtime:ro
