#============================================================================================================#
#description     : docker compose YAML file used to launch Integrations Tests for Led
#author		       :bwnyasse
#===========================================================================================================#
version: '2'
services:

    # Basic LED
    fluentd-led:
      image: bwnyasse/fluentd-led
      container_name: fluentd-led
      ports:
        - 24224:24224
        - 8080:8080
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
