name: 'led_ui'

# Intentional remove version because the version is related to LED version
# See DRAFT_VERSION_STRATEGY.md doc
# version: 0.0.1

author: <bwnyasse>

environment:
  sdk: '>=1.16.0 <2.0.0'

dependencies:
  angular2: "^2.2.0"
  browser:
  #angular: '1.1.2+2'
  #angular_ui: any
  dart_to_js_script_rewriter: "^1.0.1"
  quiver:
  xml2json: any
  jsonx: any
  js: ^0.6.0
  date:
  #ng_infinite_scroll: any
dev_dependencies:
  test:

transformers:
- angular2:
    platform_directives:
    - package:angular2/common.dart#COMMON_DIRECTIVES
    platform_pipes:
     - package:angular2/common.dart#COMMON_PIPES
    entry_points: web/main.dart
- dart_to_js_script_rewriter
- $dart2js:
    csp: true # Content Security Policy
    checked: false
    $exclude: bin
    minify: true
    commandLineOptions: ['--enable-experimental-mirrors','--trust-type-annotations', '--trust-primitives']
